modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="evolyrics"
version="1.0.0"
displayName="EvoLyrics"
displayTest="IGNORE_ALL_VERSION"
description='''Synced 3D lyrics rendered inside the Minecraft world. Client-side only.'''

[[dependencies.evolyrics]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.evolyrics]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"
